"""Russian logical labels; branded technology names remain intact."""
LABELS={'Processor':'Процессор','Storage & RAM':'Оперативная и встроенная память','Dimensions':'Габариты','Display':'Экран','Rear camera':'Основная камера','Front Camera':'Фронтальная камера','Battery & Charging':'Аккумулятор и зарядка','Cooling System':'Система охлаждения','Security':'Защита и разблокировка','Network & Connectivity':'Сотовая связь и SIM','Wireless Networks':'Беспроводная связь','Navigation & Positioning':'Навигация','Audio':'Аудио','Video':'Видео','Splash, Water and Dust Resistant':'Защита от воды и пыли','Sensors':'Датчики','Operating System':'Операционная система','Package Contents':'Комплектация','Product Name':'Название устройства','Name':'Название устройства','Product Model Number':'Номер модели устройства','Model':'Номер модели устройства','Main Unit Dimensions':'Габариты робота','Product Dimensions':'Габариты товара','Product dimensions with base':'Габариты монитора с подставкой','Station Size':'Габариты станции','Rated Power':'Номинальная мощность','Rated power':'Номинальная мощность','Rated Voltage':'Номинальное напряжение','Charging Voltage':'Напряжение зарядки','Battery Capacity':'Ёмкость аккумулятора','Main Unit Net Weight':'Вес робота без упаковки','Net Weight':'Вес товара без упаковки','Product net weight':'Вес товара без упаковки','Omni Station Model':'Номер модели станции','Rated Input':'Входные параметры станции','Rated Output':'Выходные параметры станции','Dust Compartment Capacity':'Ёмкость пылесборника','Aspect ratio':'Соотношение сторон','Power input':'Входное питание','Response time':'Время отклика','Resolution':'Разрешение экрана','Display size':'Диагональ экрана','Visible area size (diagonal)':'Диагональ видимой области','Dot pitch':'Шаг пикселя','Brightness':'Яркость','Operating temperature':'Рабочая температура','Contrast ratio':'Контрастность','Operating humidity':'Рабочая влажность','Colours':'Количество отображаемых цветов','Atmospheric pressure':'Атмосферное давление','Ports':'Порты','Rear camera photo features':'Функции фотосъёмки основной камеры','Rear camera video features':'Функции видео основной камеры','Rear camera video recording':'Режимы записи видео основной камеры','Front camera photography features':'Функции фотосъёмки фронтальной камеры','Front camera video features':'Функции видео фронтальной камеры','Front camera video recording':'Режимы записи видео фронтальной камеры','Battery':'Аккумулятор','CPU':'Процессор','GPU':'Графический процессор','Memory':'Память','Storage':'Накопитель','Product dimensions':'Габариты товара','Product weight':'Вес товара','Frequency':'Частота','Wireless standards':'Стандарты беспроводной связи','Antenna':'Антенны','Operating system':'Операционная система','Runtime (Eco)':'Заявленный максимум работы — экономичный режим','Runtime (Turbo)':'Заявленный максимум работы — турборежим','Reverse charging':'Обратная зарядка','Wired charging':'Проводная зарядка','Wireless charging':'Беспроводная зарядка','Battery capacity':'Ёмкость аккумулятора'}
LABELS.update({'Display colours':'Количество отображаемых цветов','AI features':'Функции ИИ','Cooling system':'Система охлаждения','Rear Camera':'Основная камера','Sensor':'Датчики','Smart Home':'Умный дом','Item Dimensions':'Габариты устройства','Power (air-drying + charging)':'Мощность станции — сушка и зарядка','Power (during cleaning)':'Мощность станции — очистка','Power (during dust emptying)':'Мощность станции — опустошение пылесборника','Display Type':'Тип экрана','Color gamut':'Цветовой охват','Color depth':'Глубина цвета','Refresh rate':'Частота обновления','Viewing angle':'Угол обзора','Speaker':'Динамики','Size':'Размер экрана','Color':'Цвет','Stand':'Подставка','Power button':'Кнопка питания','Dimensions including base (L × W × H)':'Габариты телевизора с подставкой (Д × Ш × В)','Dimensions not including base (L × W × H)':'Габариты телевизора без подставки (Д × Ш × В)','Packing size (L × W × H)':'Габариты упаковки (Д × Ш × В)','Base width':'Ширина подставки','Base thickness':'Глубина подставки','Weight including base(kg)':'Вес телевизора с подставкой','Weight not including base(kg)':'Вес телевизора без подставки','Packing weight(kg)':'Вес упаковки','Frame':'Рама','Wall mount':'Крепление VESA','Connectivity':'Подключения','Broadcasting system':'Система телевещания','Power':'Мощность','Voltage':'Напряжение','Storage temperature':'Температура хранения','Humidity':'Влажность','Relative humidity':'Относительная влажность','Standby power':'Мощность в режиме ожидания','ROM':'Встроенная память','Package contents':'Комплектация'})
LABELS.update({'Stand (Design)':'Тип подставки','Stand (Material)':'Материал подставки','Item Dimensions (Robot vacuum)':'Габариты робота','MEMC':'Компенсация движения MEMC','Hardware configuration':'Аппаратная конфигурация','Product dimensions':'Габариты товара'})
LABELS.update({'Charging protocols':'Протоколы зарядки','Charging port':'Порт зарядки','Battery technology':'Технология аккумулятора'})

def label(raw):
    if raw in LABELS:return LABELS[raw]
    import re
    if re.search('[а-яё]',raw,re.I) or any(x in raw for x in ('HyperOS','HyperAI','Surge','Leica','LDS','S-Cross','Dual AutoEmpty','HyperStream','NFC')):return raw
    return 'Характеристика: '+raw

def project(rows):
    result=[]
    for row in rows:
        fact=next(iter(row.get('sources',{}).values()),{});name=label(fact.get('raw_name') or row['display_name'])
        if fact.get('section')=='База / станция' and 'станци' not in name.casefold():name+=' (станция)'
        result.append({**row,'display_name':name,'xiaomi_presentation':True})
    return result
