"""Stage 17 -- render report.md from the generated queue, control and guard
artifacts, so every number in the report comes from a file next to it.

    python reports/source_census_2026-09-24_stage17/scripts/06_render_report.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
STAGE = ROOT / "reports/source_census_2026-09-24_stage17"
queue = STAGE / "queue"


def load(path):
    return json.loads(Path(path).read_text(encoding="utf-8"))


summary_file = load(queue / "coverage_summary.json")
S, META = summary_file["summary"], summary_file["meta"]
priority = load(queue / "priority_queue.json")
waves = load(queue / "waves.json")
groups = load(queue / "request_groups.json")
facts = load(queue / "family_facts.json")
controls = load(STAGE / "controls/control_summary.json")
guard = load(STAGE / "guard_matrix.json")
integrity = load(STAGE / "protected_hashes_check.json")
total = S["unique_products"]

STATUS_LABEL = {
    "ready_to_run": "ready to run (working adapter + exact URL / confirmed adapter route)",
    "adapter_url_missing": "adapter exists, exact URL missing",
    "official_route_no_adapter": "official route known, no adapter",
    "needs_product_page_fixture": "needs a Product page fixture",
    "host_blocked": "host blocked",
    "identity_conflict": "identity / variant conflict",
    "manual_review": "manual review",
}
ORDER = list(STATUS_LABEL)


def pct(n, d=total):
    return f"{100 * n / d:.2f}%"


lines = []
w = lines.append
w("# Stage 17 — offline coverage queue for the whole catalog")
w("")
w("Written for: the repository owner planning Stage 18 (adapters by group).")
w("")
w("**No HTTP requests were made in this stage.** The catalog is opened read-only "
  f"(`{META['catalog']['path']}`, SHA-256 `{META['catalog']['sha256']}`, unchanged: **{integrity['catalog_unchanged']}**). "
  "Earlier report directories (Stages 2-16) were not written to "
  f"({integrity['prior_report_directories']} directories / {integrity['prior_report_files']} files hashed in [`protected_hashes_check.json`](protected_hashes_check.json); "
  f"Stage 2-12 files that differ from Stage 13's per-file hash record: **{len(integrity['stage2_to_12_files_changed_vs_stage13_record'])}**; "
  f"earlier report files modified after this stage started: **{len(integrity['prior_report_files_modified_after_stage17_started'])}**). "
  "Everything below is regenerated by the scripts in [`scripts/`](scripts/) from files in this repository.")
w("")
w("## 1. Cleanup first: the excluded dealer, and the test network guard")
w("")
w("* **Literal name removed from active files.** `tests/`, `product_tool/`, `docs/`, `README.md` and `product_tool/config/` no longer contain it "
  f"({integrity['active_files_scanned_for_excluded_dealer']} active files scanned by word-window SHA-256, so the name is not written down even in the check; "
  f"files still naming it: **{len(integrity['active_files_naming_it'])}**). "
  "The general rule *a source outside the approved list is not used* stays, now stated without a shop name: "
  "`tests/_source_policy.py` holds `APPROVED_SOURCE_IDS` and `hosts_outside_allowlist()`; the catalog/registry tests compare source ids to the approved list "
  "and the frozen request-log tests compare contacted hosts to each stage's own allowed hosts. The two tests that read a frozen Stage 11.3 card now pin the exact bytes of "
  "the statement they check (SHA-256) instead of matching prose. Six one-off census report scripts had the name inside generated prose; "
  "that sentence now says \"the dealer exclusion\" (text only, no behaviour change).")
w("* **Untouched on purpose:** everything under `reports/` (immutable history), and `data/batches.sqlite3`, a local run database that still holds "
  "rows from an earlier LG run with the old source key. That is user data, not code or config; it is outside the scan and I did not edit it.")
w("* **Re-pinned honestly.** Editing those files changed their hashes, which the Stage 8/11.5/12 protection tests pin. "
  "`tests/_pipeline_migration.py` documents each change with a reason and the hashes were refreshed by "
  "[`scripts/01_repin_migration_hashes.py`](scripts/01_repin_migration_hashes.py); "
  f"all {len(integrity['pinned_files'])} pinned files match: **{integrity['pinned_all_ok']}**. `worker.py` also gained two constants "
  "(`LG_BRAND_ALIASES`, `HYPERX_BRAND_ALIASES`, identical contents) so the planner reads the real dispatch table.")
w("")
w("### Test network guard — which commands guarantee it")
w("")
w("The guard (`tests/_bootstrap.py`) blocks real HTTP (`HTTPAdapter.send`) **and** DNS/socket connects to anything but loopback, "
  "so `urllib`/`http.client` and stray lookups are covered too. It is switched on by importing the `tests` package, "
  "i.e. **before any test module loads**, instead of relying on `test_000_network_safety.py` sorting first.")
w("")
w("| Command | Guard on before the first test loads? | Evidence |")
w("|---|---|---|")
for mode, item in guard["probes"].items():
    verdict = "**yes — guaranteed** (package import)" if item["guard_on_before_any_test_runs"] and item["package_imported"] else (
        "only through `test_000_network_safety.py` being first" if item["guard_on_before_any_test_runs"] else "**no**")
    w(f"| `{item['command']}` | {verdict} | probe `{mode}` in [`guard_matrix.json`](guard_matrix.json) |")
w("")
for name, run in guard["full_runs"].items():
    w(f"* `{name}` → returncode {run['returncode']}: {' / '.join(x.strip() for x in run['summary'] if x.strip())}")
w("")
w("The legacy command `python -m unittest discover -s tests` still passes and is still protected in a full run, but **that protection is order-dependent**: "
  "with a narrowed `-p` pattern that excludes `test_000_network_safety.py` the probe shows the guard off. Use `python -m tests` (README updated).")
w("")
w("## 2. What is measured")
w("")
w(f"Unit of work = one unique catalog product ({total:,}; key: brand casefolded + category + seller article, as the workbook's own «Контекст» sheet defines it) "
  f"and one brand-category pair ({S['brand_category_pairs']:,}). Totals reconcile with the workbook: "
  f"{META['reconciliation']['observed']['unique_products']:,} products, {META['reconciliation']['observed']['source_rows']:,} rows, "
  f"{META['reconciliation']['observed']['brands']} brands, {META['reconciliation']['observed']['categories']} categories, "
  f"{META['reconciliation']['observed']['brand_category_pairs']:,} pairs, and every pair's product count equals the «Бренд_Категория» sheet.")
w("")
w("### Coverage")
w("")
w("| Status | Unique products | % | Brand-category pairs |")
w("|---|---:|---:|---:|")
for status in ORDER:
    w(f"| {STATUS_LABEL[status]} | {S['units_by_status'][status]:,} | {pct(S['units_by_status'][status])} | {S['pairs_by_status'][status]:,} |")
w(f"| **Total** | **{total:,}** | 100% | **{S['brand_category_pairs']:,}** |")
w("")
ready = S["units_by_status"]["ready_to_run"]
w(f"**Really ready to run: {ready:,} products ({pct(ready)}), {S['pairs_fully_ready']} pairs fully ready, {S['pairs_partially_ready']} more partially ready.** "
  f"Of the {ready} ready products, {S['ready_units_by_url_basis'].get('adapter_discovery', 0)} are LG rows the LG adapter resolves itself (sitemap / model template — "
  "\"ready\" means *can be run*, not *will be found*), and "
  f"{S['ready_units_by_url_basis'].get('known_url_map', 0)} are HyperX rows with a human-confirmed exact URL. "
  "Waiting for a URL: "
  f"{S['units_by_status']['adapter_url_missing']} (HyperX, adapter exists). Waiting for an adapter: {S['units_by_status']['official_route_no_adapter']:,}. "
  f"Waiting for a fixture: {S['units_by_status']['needs_product_page_fixture']:,}. Blocked host: {S['units_by_status']['host_blocked']:,}. "
  f"Conflict: {S['units_by_status']['identity_conflict']}. Manual decision: {S['units_by_status']['manual_review']:,}.")
w("")
w("Reasons behind each status:")
w("")
for status in ORDER:
    parts = ", ".join(f"`{reason}` {count:,}" for reason, count in S["reasons"][status].items())
    w(f"* **{status}** — {parts}")
w("")
w("Risk flags carried on units (they do not change the status): "
  + ", ".join(f"`{k}` {v:,}" for k, v in S["flags"].items())
  + ". Dealer exact URLs on record: "
  f"{S['units_with_dealer_exact_url']} unit (DNS, HyperX 9A273AA) — stored separately as `dealer_exact_urls`, never as the official URL.")
w("")
w("## 3. Priority brands")
w("")
w("The list is the priority list recorded in Stage 8 (`structural_report_v8.py` PRIORITY), in that order; edit it in "
  "`product_tool/config/coverage_planner.v1.json` and re-run the planner to re-rank. `recommended_rank` puts unblocked brands with the most movable products first and blocked brands last.")
w("")
w("| # | Family | Products | Status mix | Template group | Wave | Recommended rank |")
w("|---:|---|---:|---|---|---|---:|")
for row in priority:
    mix = ", ".join(f"{k} {v}" for k, v in row["unit_status_counts"].items()) or ("no catalog labels (Xbox is catalogued under Microsoft)" if row["family"] == "xbox" else "—")
    w(f"| {row['user_order']} | {row['family']} | {row['unique_products']:,} | {mix} | {row['template_group'] or '—'} | {row['wave_id'] or '—'} | {row['recommended_rank']} |")
w("")
w("## 4. Requests are grouped, not repeated")
w("")
not_ready = total - ready
w(f"{not_ready:,} products are not ready; they fall into **{len(groups)} request groups** (one message each) keyed by status, reason, brand/family, category group and host — "
  f"about {not_ready / len(groups):.0f} products per message instead of {not_ready:,} messages. Groups by kind: "
  + ", ".join(f"{kind} {sum(1 for g in groups if g['kind'] == kind)}" for kind in ("ask_user", "capture_fixture", "dev_task", "human_decision")) + ".")
w("")
w("Largest groups:")
w("")
w("| Products | Kind | Status / reason | Brand family | Category group | Host |")
w("|---:|---|---|---|---|---|")
for g in sorted(groups, key=lambda g: (-g["units"], g["group_id"]))[:10]:
    w(f"| {g['units']:,} | {g['kind']} | {g['status']} / `{g['reason']}` | {g['subject']} | {g['category_group']} | {g['host'] or '—'} |")
w("")
w("The URL ask for the existing adapter is one group per HyperX category group: "
  + "; ".join(f"“{g['message_ru']}”" for g in groups if g["status"] == "adapter_url_missing") + " Full list: [`queue/request_groups.json`](queue/request_groups.json).")
w("")
w("## 5. First adapter wave per confirmed Product page template")
w("")
w("Groups are the Stage 13 template groups (A–D), corrected by Stage 15 for HyperX. Each wave lists the catalog gain, what is guaranteed, what is only an upper bound, and what must exist first. "
  "Full per-family and per-category numbers: [`queue/waves.json`](queue/waves.json).")
w("")
for wave in waves:
    g = wave["expected_gain"]
    w(f"### {wave['wave_id']} — group {wave['group_id']}: {wave['group_title']}")
    w("")
    w(f"* Families in this wave: {', '.join(wave['families'])}" + (f" (later: {', '.join(wave['later_wave_families'])})" if wave["later_wave_families"] else "") + f". Template source: `{wave['template_source']}`.")
    w(f"* **Expected gain:** {g['adapter_coverage_units']:,} products / {g['adapter_coverage_pairs']} pairs ({g['adapter_coverage_pct']}% of the catalog) gain a working adapter. "
      f"Guaranteed `ready_to_run` from exact URLs already on record: **{g['ready_guaranteed_by_urls_on_record_units']}**. "
      f"Up to **{g['ready_via_confirmed_discovery_route_units']:,}** ({g['ready_via_confirmed_discovery_route_pct']}%) become ready through a confirmed discovery route; "
      f"otherwise they wait as `adapter_url_missing` until exact URLs exist (upper bound if every URL is supplied: {g['ready_if_every_exact_url_is_supplied_units']:,}).")
    for item in wave["per_family"]:
        need = "; ".join(item["prerequisites"])
        w(f"  * `{item['family']}`: {item['addressable_units']:,} products, {item['addressable_pairs']} pairs, {len(item['categories_in_scope'])} categories; "
          f"moves to `{item['moves_to_after_adapter']}`; fixture level `{item['fixture_level']}`"
          + (f" (missing: {', '.join(item['fixture_missing_layers'])})" if item["fixture_missing_layers"] else "")
          + f". Needs: {need}")
    w(f"* Shared: {', '.join(wave['shared_primitives']) or 'nothing yet'}. Stays separate: {', '.join(wave['stays_separate'])}.")
    w("")
w("### Adapter readiness criteria (identical for every wave, measured per family)")
w("")
for c in waves[0]["readiness_criteria"]:
    w(f"{waves[0]['readiness_criteria'].index(c) + 1}. **{c['id']}** — {c['text']}")
w("")
w("Razer stays out of every wave while its host is stopped (Stage 13 §1); Stage 12's Razer page data is not counted as evidence anywhere in the queue.")
w("")
w("## 6. run_once() bridge with checkpoints — offline controls")
w("")
w("Controls run through `executor.run_units()` → `jobs.enqueue()` → the ordinary `worker.run_once()`. HyperX rows are answered from the **real** pages saved in Stages 11/11.1 "
  "(`reports/.../raw/*.html.txt`); LG runs the real `LGAdapter`, `LGRUAdapter` and `SulpakAdapter` against in-memory pages on a real catalog row. "
  "[`controls/`](controls/) holds the checkpoints; every call was served from memory with the offline guard on.")
w("")
w("| Row | Plan status | Outcome | Reason / result |")
w("|---|---|---|---|")
main = load(STAGE / "controls/control_checkpoint_main.json")["units"]
for entry in sorted(main.values(), key=lambda e: (e["catalog_row"], e["seller_sku"])):
    result = entry.get("card")
    detail = entry["stop_code"] or "done"
    if result:
        detail += f" — sources: " + ", ".join(f"{s['source_key']}={s['match_level']}" for s in result["sources"] if s["source_key"] != "dns") + f"; facts {result['facts']}, photos {result['photos']}, gaps: {', '.join(result['gaps']) or 'none'}"
    forced = " (forced through run_once() as if a URL had been supplied)" if entry["catalog_row"] >= 100000 else ""
    w(f"| HyperX `{entry['seller_sku']}`{forced} | {entry['plan_status']} | {entry['outcome']} | {detail} |")
lg = next(iter(load(STAGE / "controls/control_checkpoint_lg.json")["units"].values()))
w(f"| LG `{lg['seller_sku']}` | {lg['plan_status']} | {lg['outcome']} | job {lg['job_status']} — sources: " + ", ".join(f"{s['source_key']}={s['match_level']}" for s in lg["card"]["sources"] if s["source_key"] != "dns") + f"; facts {lg['card']['facts']}, gaps: {', '.join(lg['card']['gaps'])} |")
stop = load(STAGE / "controls/control_checkpoint_host_stop.json")["units"]
for entry in sorted(stop.values(), key=lambda e: e["seller_sku"]):
    w(f"| HyperX `{entry['seller_sku']}` (host-stop control) | {entry['plan_status']} | {entry['outcome']} | {entry['stop_code']} — {entry.get('stop_detail', '')[:110]} |")
w("")
w(f"* Resume: a second pass over the finished checkpoint made **0** new calls (`hyperx_fixture_calls` stays {len(controls['network']['hyperx_fixture_calls'])}: one per confirmed row).")
w(f"* Host stop after a 403 survives a restart: the second unit ran with a brand-new adapter and session and made **{len(controls['network']['calls_after_restart_on_a_stopped_host'])}** calls.")
w("* A unit in a non-runnable status is never handed to `run_once()` (no job is created); the checkpoint stores the exact reason instead.")
w("")
w("## 7. Measuring the next stage")
w("")
w("`python -m product_tool.coverage plan --out <dir>` after each adapter/URL change, then "
  "`python -m product_tool.coverage delta --before queue/coverage_units.jsonl --after <dir>/coverage_units.jsonl` lists the status moves and the `ready_to_run` gain. "
  "A wave is done when the moves match its `expected_gain`, no unit enters `ready_to_run` without a positive fixture, and all nine criteria in §5 pass.")
w("")
w("## 8. What this stage did not do, and things to know")
w("")
w("* No new URL was found, no adapter was written, no brand was researched: HyperX is still 2 of 41 rows with exact URLs.")
w("* Profile statuses in `adapter_profiles.v1.json` were used as recorded except where Stage 13 proved them stale (Samsung, PlayStation, Microsoft, Razer); those overrides name their evidence in `product_tool/config/coverage_planner.v1.json`.")
w("* 233 units carry `sku_repeated_halves` (the article is the same token twice, e.g. `ES602-Black(М)ES602-Black(М)`). Only the four LG ones are stopped (`seller_sku_not_a_manufacturer_code`), because the LG adapter searches by manufacturer code; the rest are flagged for the adapters to decide.")
w("* 966 units have alternate titles; that is a flag, not a conflict. `identity_conflict` here means a shared seller article across catalog units (68) or a confirmed evidence conflict (1).")
w("* Mid-task incident: a stray `git checkout README.md` reverted the README's uncommitted changes. I rebuilt them from the earlier session's transcript (three sentences that dropped the removed dealer's name); the diff before the mistake was 3 lines and the restored diff is the same 3 lines, but please glance at `git diff README.md`.")
w("")
w("## Artifacts")
w("")
w("* [`queue/coverage_summary.json`](queue/coverage_summary.json), [`queue/coverage_units.jsonl`](queue/coverage_units.jsonl) (one line per unique product), [`queue/coverage_pairs.json`](queue/coverage_pairs.json), [`queue/priority_queue.json`](queue/priority_queue.json), [`queue/waves.json`](queue/waves.json), [`queue/request_groups.json`](queue/request_groups.json), [`queue/family_facts.json`](queue/family_facts.json)")
w("* [`controls/`](controls/), [`guard_matrix.json`](guard_matrix.json), [`protected_hashes_check.json`](protected_hashes_check.json), [`tests.txt`](tests.txt)")
w("* Code: `product_tool/coverage/`, `product_tool/offline_guard.py`, `product_tool/config/coverage_planner.v1.json`, `tests/_bootstrap.py`, `tests/__init__.py`, `tests/__main__.py`, `tests/_source_policy.py`, `tests/coverage_controls.py`, `tests/test_coverage_queue.py`; docs: `docs/COVERAGE_QUEUE_V17.md`")

(STAGE / "report.md").write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
print("report.md:", len(lines), "lines")
